export interface PredictionData {
    date: string;
    actual?: number;
    predicted: number;
    confidence: number;
}

export interface ForecastRequest {
    timeRange?: 'day' | 'week' | 'month';
    productId?: number;
}

export interface ForecastResponse {
    predictions: PredictionData[];
}

export interface WastePrediction {
    productId: number;
    productName: string;
    currentStock: number;
    expirationDate: string;
    wasteRisk: 'low' | 'medium' | 'high';
    recommendedAction: string;
    confidence: number;
}

/**
 * Intelligence API Service
 * Handles all AI/ML-powered forecasting and prediction endpoints
 */
import { db } from '@/lib/firebase';
import { collection, query, where, getDocs, orderBy, limit } from 'firebase/firestore';

// ... interfaces ...

/**
 * Intelligence API Service
 * Handles all AI/ML-powered forecasting and prediction endpoints
 */
export class IntelligenceAPI {
    /**
     * Generate sales predictions using historical data
     */
    static async generateSalesPredictions(request: ForecastRequest = {}): Promise<ForecastResponse> {
        try {
            // Fetch real forecasts from Firestore (generated by Python worker)
            // Hardcoding tenant for demo, in real app pass user.uid
            const tenantId = 'demo-user';
            const q = query(
                collection(db, 'forecasts'),
                where('tenant_id', '==', tenantId),
                orderBy('date', 'asc'),
                limit(30)
            );

            const snapshot = await getDocs(q);

            if (!snapshot.empty) {
                const predictions: PredictionData[] = snapshot.docs.map(doc => {
                    const data = doc.data();
                    return {
                        date: data.date,
                        predicted: data.predicted_mean,
                        confidence: 90 // Mock or calculate from bounds
                    };
                });

                return { predictions };
            }

            console.warn("No real forecasts found, falling back to mocks.");
            return this.getMockPredictions(request.timeRange || 'week');

        } catch (error) {
            console.error("Error fetching forecasts:", error);
            // Return mock data as fallback
            return this.getMockPredictions(request.timeRange || 'week');
        }
    }

    /**
     * Predict waste risk for products
     */
    static async predictWaste(): Promise<WastePrediction[]> {
        // Mock implementation for Firebase migration
        return this.getMockWastePredictions();
    }

    /**
     * Mock predictions for development/demo
     */
    private static getMockPredictions(timeRange: string): ForecastResponse {
        const intervals = timeRange === 'day' ? 24 : timeRange === 'week' ? 7 : 30;
        const predictions: PredictionData[] = [];
        const now = new Date();

        for (let i = 0; i < intervals; i++) {
            const date = new Date(now);
            date.setDate(date.getDate() + i);

            predictions.push({
                date: date.toISOString(),
                actual: i < intervals / 2 ? Math.random() * 1000 + 500 : undefined,
                predicted: Math.random() * 1000 + 600,
                confidence: Math.max(60, 95 - i * 2),
            });
        }

        return { predictions };
    }

    /**
     * Mock waste predictions for development/demo
     */
    private static getMockWastePredictions(): WastePrediction[] {
        return [
            {
                productId: 1,
                productName: 'Fresh Milk',
                currentStock: 45,
                expirationDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
                wasteRisk: 'high',
                recommendedAction: 'Discount by 30% or donate',
                confidence: 0.87,
            },
            {
                productId: 2,
                productName: 'Organic Bread',
                currentStock: 23,
                expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
                wasteRisk: 'high',
                recommendedAction: 'Create surprise bag',
                confidence: 0.92,
            },
            {
                productId: 3,
                productName: 'Fresh Vegetables',
                currentStock: 67,
                expirationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
                wasteRisk: 'medium',
                recommendedAction: 'Monitor closely',
                confidence: 0.75,
            },
        ];
    }
}
