export const kpiDefinitions: Record<string, string> = {
    "Net Profit": "Total earnings after all operating expenses, taxes, and costs have been deducted. It's the 'bottom line' of your business profitability.",
    "Operations Efficiency": "A measure of how effectively your business converts resources (like time and labor) into revenue and results.",
    "Waste Reduction": "The percentage by which product waste or expiration has been decreased compared to previous periods. Essential for sustainability.",
    "Inventory Turnover": "How many times your entire inventory is sold and replaced during a specific time period. Higher is usually better.",
    "Total Sales": "The total gross revenue generated from all customer transactions during the selected period.",
    "Transactions": "The total number of individual sales or service interactions completed with customers.",
    "Profit": "The surplus remaining after accounting for the cost of goods sold and operating expenses.",
    "Revenue": "The total income generated by the sale of goods or services before any expenses are deducted.",
    "Avg Order Value": "The average amount of money spent by a customer each time they place an order.",
    "ESG Score": "A metric evaluating your environmental, social, and governance impact. High scores indicate sustainable and ethical operations.",
    "Sustainability Impact": "A holistic measure of how your business operations contribute to environmental conservation and social responsibility.",
    "Compliance Score": "Your level of adherence to local regulations, including digital invoicing (FacturaE) and anti-fraud logging (Veri*factu).",
    "Customer Satisfaction": "A metric reflecting how products or services provided by your company meet or surpass customer expectation.",
    "Risk Level": "Calculated probability of operational or financial issues based on current trends and historical data.",
    "Order Accuracy": "The percentage of orders that are processed and delivered without errors in items or quantities.",

    // Spanish Definitions for Dashboard
    "Ventas Totales": "Ingresos brutos totales generados por todas las transacciones de clientes durante el periodo seleccionado.",
    "Transacciones": "Número total de ventas individuales o interacciones de servicio completadas con clientes.",
    "Beneficio": "Ganancia neta restante después de deducir el costo de los bienes vendidos y los gastos operativos.",
    "Ahorro Operativo": "Reducción de costos lograda mediante la optimización de procesos y reducción de desperdicios.",
    "Ingresos": "Entrada total de dinero por la venta de bienes o servicios antes de deducir cualquier gasto.",
    "Valor Promedio Pedido": "Monto promedio gastado por un cliente cada vez que realiza un pedido.",

    // Sustainability & Insights (Spanish)
    "CO₂ Ahorrado": "Cantidad estimada de emisiones de dióxido de carbono evitadas gracias a la prevención de desperdicio.",
    "Merma Reducida": "Porcentaje o cantidad de producto que se evitó desperdiciar en comparación con periodos anteriores.",
    "Ahorro de Costes": "Dinero ahorrado directamente al evitar la pérdida de inventario y optimizar compras.",
    "Desperdicio de Alimentos Reducido": "Cantidad física de alimentos (en kg o unidades) que se salvó de ser desechada.",
    "Tasa de Conversión": "Porcentaje de visitantes o clientes potenciales que completaron una compra.",
    "Tasa de Devolución": "Porcentaje de productos vendidos que fueron devueltos por los clientes.",
    "Satisfacción del Cliente": "Métrica basada en reseñas y feedback que indica qué tan contentos están los clientes.",

    // Definitions for Surprise Bags & Rating Insight Cards (Mixed English Labels in UI)
    "Active Surprise Bags": "Bolsas sorpresa activas actualmente disponibles para la venta en la aplicación.",
    "Surprise Bag Revenue": "Ingresos totales generados específicamente por la venta de bolsas sorpresa.",
    "Food Waste Prevented": "Cantidad estimada de comida (en kg) salvada gracias a la venta de bolsas sorpresa.",
    "Environmental Impact": "Impacto ambiental positivo calculado en base a la comida salvada (emisiones de CO2 evitadas).",
    "Surprise Bag rating": "Valoración promedio (0-5 estrellas) dada por los clientes específicamente a las bolsas sorpresa.",
    "Store experience rating": "Calificación general de la experiencia en tienda según feedback recolectado de clientes.",
    "Cancellations": "Porcentaje de pedidos que fueron cancelados antes de ser completados o recogidos.",
    "Refunds": "Porcentaje de pedidos que resultaron en un reembolso al cliente por cualquier motivo.",

    // Engine & Widget Definitions (Spanish)
    "Previsión de Demanda": "Analiza patrones históricos y estacionales para predecir la demanda futura de cada producto con alta precisión.",
    "Precios Óptimos": "Sugiere ajustes de precios en tiempo real para maximizar ganancias y rotación de stock basándose en elasticidad y competencia.",
    "Previsión de Ventas - Próximos 7 Días": "Proyección detallada de ingresos esperados para la próxima semana, considerando eventos y tendencias.",
    "Niveles de Inventario Óptimos": "Recomendaciones de stock ideal para evitar roturas y excesos, minimizando costes de almacenamiento.",
    "Resumen de Riesgos": "Evaluación integral de riesgos operativos, incluyendo volatilidad del mercado y fiabilidad de proveedores.",
    "Factores Clave de Influencia": "Variables externas (clima, eventos, festivos) que están impactando positiva o negativamente en las ventas.",
    "Predicción de Visitantes": "Estimación de tráfico de clientes por hora para optimizar personal y tiempos de preparación.",
    "Productos Top - Previsión vs Stock": "Lista de artículos más vendidos comparando su stock actual con la demanda esperada.",
    "Meteorología Local": "Condiciones climáticas en tiempo real y previsión a corto plazo, útil para anticipar cambios en la demanda de ciertos productos.",
    "Visitor Prediction": "Forecast of customer traffic per hour to optimize staffing and preparation times.",

    // Predictive Analytics & Pricing
    "Matriz de Correlación": "Identifica qué productos suelen comprarse juntos para sugerir bundles y promociones cruzadas.",
    "Predicción de Mermas": "Estima la cantidad de producto que podría desperdiciarse en los próximos días si no se toman medidas.",
    "Monitorización en Tiempo Real": "Visualización en vivo de ventas, stock y precios de la competencia para decisiones inmediatas.",
    "Automatización por Caducidad": "Reglas para ajustar precios automáticamente cuando un lote se acerca a su fecha de expiración.",
    "Precios por Zona": "Estrategias de precios diferenciadas según la ubicación geográfica de la tienda o cliente.",
    "Historial de Precios": "Gráfico evolutivo de los cambios de precio y su impacto en la demanda a lo largo del tiempo.",
    "Simulador de Precios": "Herramienta para proyectar cómo cambios en el precio afectarían el margen y volumen de ventas.",
    "Calendario de Eventos": "Eventos locales y festivos próximos que podrían influir en el tráfico y la demanda.",
    "Factores Climáticos": "Análisis de cómo el clima actual y pronosticado afecta el comportamiento de compra.",

    // Autopilot
    "Control de Piloto Automático": "Panel central para activar o desactivar los agentes autónomos de precios e inventario.",
    "Cola de Sincronización": "Lista de cambios de precio pendientes de ser enviados al TPV o eCommerce.",
    "Registro de Acciones": "Log detallado de todas las decisiones tomadas automáticamente por el sistema.",

    // Compliance Hub
    "Nivel de Cumplimiento": "Estado general de adecuación a la Ley 1/2025 y normativas locales de residuos.",
    "Alertas de Cumplimiento": "Notificaciones urgentes sobre plazos legales, documentos faltantes o cuotas no cumplidas.",
    "Historial de Planes": "Repositorio de versiones anteriores del Plan de Prevención de Desperdicio Alimentario.",
    "Gestión de Donaciones": "Herramientas para coordinar entregas a ONGs y banos de alimentos.",
    "Convenios de Donación": "Contratos activos con entidades receptoras autorizadas para donaciones.",
    "Propuestas de Donación Pendientes": "Lotes de alimentos disponibles esperando aceptación por parte de una ONG.",
    "Registros de Donación": "Historial oficial de entregas realizadas con sus correspondientes certificados.",
    "Registro de Pérdidas y Mermas": "Libro digital obligatorio para registrar y justificar cualquier alimento desechado.",
    "Gestor de Residuos": "Información y contratos con las empresas autorizadas para la recolección de residuos.",
    "Registro de Formación del Personal": "Evidencias de capacitación a empleados sobre protocolos de prevención de desperdicio.",
    "Inventario de Productos": "Gestión completa del stock con alertas de caducidad y sugerencias de acción."
};
