
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiehjbbdeyngslfpgfnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZWhqYmJkZXluZ3NsZnBnZm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NDQxNzAsImV4cCI6MjA1NjMyMDE3MH0.s2152q-oy3qBMsJmVQ8-L9whBQDjebEQSo6GVYhXtlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configuración para persistencia entre aplicaciones
const supabaseOptions = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'wisebite_app_auth',
  }
};

// Define custom function types to extend the default Supabase types
type CustomFunctions = {
  broadcast_order_status_change: (args: { 
    order_id: string; 
    new_status: "pending" | "accepted" | "completed" | "rejected"
  }) => Promise<{ data: any; error: any }>
}

// Create the client with extended types
export const supabase = createClient<Database, "public", CustomFunctions>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  supabaseOptions
);
